### ISSUE TITLE
review java spotbugs performance

### ISSUE THREAD

**Issue by Anthony-Mckale** [RiverSafeUK/eze-cli#113]
spotbugs historically has had very poor performance takign upto 20 mins to finish a scan

- look into how to improve this

- any alternatives aka semgrep ?

- benefits of spotbugs it's self

carry out changes as required

**Comment by patrick-morris** [comment]
In order to run Java-Spotbugs locally you will need to install Maven.

You can download a .zip using the link below:

https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.zip

Installation instruction here (Don't forget to update your PATH environment variable)

https://maven.apache.org/install.html


Maven is effectively a plugin execution framework. We'll be using v4.7.3 of the spotbugs-maven-plugin.

Command to run locally: (The command is expecting a directory with a POM file present)

`mvn -B -Dmaven.javadoc.skip=true -Dmaven.test.skip=true install com.github.spotbugs:spotbugs-maven-plugin:check`

**Output:**

```
[INFO] Fork Value is true
[INFO] Done SpotBugs Analysis....
[INFO]
[INFO] <<< spotbugs-maven-plugin:4.7.3.0:check (default-cli) < :spotbugs @ goat-java <<<
[INFO]
[INFO]
[INFO] --- spotbugs-maven-plugin:4.7.3.0:check (default-cli) @ goat-java ---
[INFO] BugInstance size is 0
[INFO] Error size is 0
[INFO] No errors/warnings found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  29.844 s
[INFO] Finished at: 2022-12-28T14:03:50Z
[INFO] ------------------------------------------------------------------------
```


**Docker command:**

`docker run --rm -v /c/dev/repos/eze-goats/goat-java/insecure:/root/.m2 -v C:\dev\repos\eze-goats\goat-java\insecure:/src -w /src --rm maven:3.3-jdk-8 mvn -B -Dmaven.javadoc.skip=true -Dmaven.test.skip=true install com.github.spotbugs:spotbugs-maven-plugin:check`

**Output:**

```
[INFO] Done SpotBugs Analysis....
[INFO]
[INFO] <<< spotbugs-maven-plugin:4.7.3.0:check (default-cli) < :spotbugs @ goat-java <<<
[INFO]
[INFO] --- spotbugs-maven-plugin:4.7.3.0:check (default-cli) @ goat-java ---
[INFO] BugInstance size is 0
[INFO] Error size is 0
[INFO] No errors/warnings found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:58 min
[INFO] Finished at: 2022-12-28T13:31:41+00:00
[INFO] Final Memory: 43M/536M
[INFO] ------------------------------------------------------------------------
```

**Comment by patrick-morris** [comment]
@Anthony-Mckale - I think I might need some context here please... 

**"spotbugs historically has had very poor performance taking up to 20 mins to finish a scan"**

I've triggered spotbugs against the Eze-Goats repo, the initial run took some time to download required dependencies etc stored in the .m2 directory, the second run only took a few seconds to execute.

**Comment by patrick-morris** [comment]
Interesting article here on migrating Java SAST coverage from SpotBugs to Semgrep:

https://gitlab.com/gitlab-org/gitlab/-/issues/352666

**Comment by patrick-morris** [comment]
Java-SpotBugs fails to run if it encounters an invalid POM file e.g. "C:\dev\repos\eze-goats\goat-java\damaged-pom\pom.xml"

The error itself is being printed to STDOUT and not STDERR. This will require a workaround to address as it will cause EZE CLI to fail otherwise. 

We ran Java-Spotbugs within the insecure directory which only has a handful of dependencies. The process took nearly 4 minutes to execute. When compared to SEMGREP, we ran semgrep from the root directory of Eze-Goats, and the process completed within 6 minutes. See below results. 

Semgrep running via docker (eze-goats) repo

| Name    | Type | Critical | High | Medium | Low | Ignored | Warnings | Time   |
| ------- | ---- | -------- | ---- | ------ | --- | ------- | -------- | ------ |
| semgrep | SAST | 0        | 48   | 54     | 37  | 0       | False    | 357.6s |

Following the optimisation work which has already been carried out for Semgrep this is the recommended alternative to Java-Spotbugs. I advise we deprecate the Java-SpotBugs tool from our Eze codebase. This will require a coordinated effort from the team to ensure a clean removal.
