### ISSUE TITLE
make install leads to the use of Python 2

### ISSUE THREAD

**Issue by myvali998** [RiverSafeUK/eze-cli#37]
Hello,

I run the following command:

make install

This calls the following python command

python -m pip install -r requirements-dev.txt  -r requirements.txt && pre-commit install

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.

**ERROR: Could not find a version that satisfies the requirement black==21.5b1 (from -r requirements-dev.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for black==21.5b1 (from -r requirements-dev.txt (line 1))**

Is there a way to ensure by default when you run make install, it uses Python 3 rather than Python 2, so something like:
python -m pip3 install -r requirements-dev.txt  -r requirements.txt && pre-commit install

**Comment by Anthony-Mckale** [comment]
This is down to your machine setup, typically i make sure i'm using pyenv so my python and pip are always python3

i'm personally often using pyenv/venv to make sure i'm got python 3 installed on path.

Don't suppose you're on a mac, know they deploy v2 == python/pip and v3 == python3/pip3

The cross os locations of files is a bit difficult, on a valiana windows install python3 doesn't exist only a python which maps to python3, with pip and pip3 both pointing to a common python 3 pip

We could add a bit of auto detection for the python3 version, aka lots of which python3 && python3 --version etc etc

If you create a pull request i'll take a look at, otherwise i can add it to the backlog
